sudo: required
language: node_js
branches:
  only:
  - master
node_js: 
  - "stable"  
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - mongo test --eval 'db.users.insertOne({name:"Magesh",user_id:1,email_id:"mageshchandru35@gmail.com"});'
jobs:
  include:
    - stage: "Test"
      script:
        - echo "Running test"
        - npm test
