sudo: required
language: node_js
branches:
  only:
  - master
node_js: "node"  
services: mongodb  
cache:  
  directories:
    - "node_modules"
  yarn: true
install:
  - npm install
script:
  - npm test 